### ISSUE TITLE
Binder error 

### ISSUE THREAD

**Issue by zelenkastiot** [courtois-neuromod/anat-processing-book#16]
I think that there is an error in the JupyterLab MyBinder session since we moved the files out of the root: 

![image](https://user-images.githubusercontent.com/37374247/127220269-2752e7c3-34b2-491b-807f-c91772265619.png)

Possible solutions I can think of are: 
- have all the files in the root in a new branch, which would be edited here: 

https://github.com/courtois-neuromod/anat-processing-book/blob/b2b2046823ec75a17c697252e27adf4154d3d558/_config.yml#L33

- have them in the root of <code>main</code> like they were

**Comment by jcohenadad** [comment]
ooops! 😬  Sorry.

Is that something that you can change on your Binder config?  For example, when I compile locally with the sources moved, I just point to the source folder:
~~~
jupyter-book build source/
~~~

Also, what do you use Binder for?

I changed it because I found it cleaner to enclose the source of the book at one location (ie: separate from the jupyter book config files). Other projects seem to also do it:
- https://github.com/executablebooks/quantecon-example
- https://github.com/YannDubs/Neural-Process-Family
- https://github.com/INRIA/scikit-learn-mooc

**Comment by zelenkastiot** [comment]
No worries, we use Binder for reproducing the plots from the notebooks. We don't have to use it, we can use Google Colab instead. I have both linked 😄 

![image](https://user-images.githubusercontent.com/37374247/127299291-940dc006-9b32-4121-a09a-38929efed2c5.png)

**Comment by zelenkastiot** [comment]
I fixed the error when running the notebook on Binder. I added the path of the book inside the config! 

https://github.com/courtois-neuromod/anat-processing-book/blob/150eea141e7cb34d07059b6e6c10332127770dae/source/_config.yml#L49

I will close this issue.
