### ISSUE TITLE
Pandas DataFrame declared is not used to generate the plot

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#20]
Here:

![image](https://user-images.githubusercontent.com/2482071/127355887-30a4df36-f3bc-4136-a408-dd687de36e7b.png)

In section 1, a pandas dataframe is declared as "df", however this variable is not used in section 2 (below) that is responsible to generate the plot. 

Maybe it is related to fact that the data used to declare the dataframe are in fact never used to generate the plot? Possibly related to #19

**Comment by zelenkastiot** [comment]
Hi @jcohenadad, so this is another "trick". Here is the notebook: https://nbviewer.jupyter.org/github/courtois-neuromod/anat-processing-book/blob/main/source/results/1-test.ipynb

As you can see here in these cells (open the link above since the resolution is small): 
![image](https://user-images.githubusercontent.com/37374247/127540299-a48a22dc-2def-42bc-a5a7-8c4eb4e74a1b.png)

I use the data frame and modify it in order to be able to display the plots since there is now a specific column for <code>Subject</code>, <code>Session</code> and I have to extract them from the directory column. 

The trick is, there are [cell-tags](https://jupyterbook.org/interactive/hiding.html?highlight=hide), which when added do something to the cells (hide, remove, etc.). For a more elegant look, I have them removed but if you download the notebook (for example <code><a href="https://github.com/courtois-neuromod/anat-processing-book/blob/main/source/results/1-test.ipynb">1-test.ipynb</a></code> you can see all the cells inside 😄

**Comment by jcohenadad** [comment]
I see... to be honest I find it rather confusing because readers of the book might want to copy paste the code to reproduce it and they won't be able to do it. And looking at the entire jupyter book, there is a _lot_ of lines responsible for data reformatting, custom plotting, etc. @mathieuboudreau what was your approach when you did the T1 mapping book? Did you also have hidden cell? Was the main objective to have an interactive book and not assuming that readers would play with the backend code?

**Comment by mathieuboudreau** [comment]
I'm not sure I fully understand some of the discussion in this issue, but I can say that there were some parts of my books that were more suitable to being run in the Jupyter Book directly than others (e.g. long simulations). My preference has always been to *show* the code in the Jupyter Book, but to recommend users use the MyBinder/Jupyter platform directly if they want to edit code. We can discuss a bit more tomorrow and maybe clarify the part I don't fully understand here tonight. @zelenkastiot are you joining the call tomorrow/Friday as well?

**Comment by zelenkastiot** [comment]
Yes, I will!

**Comment by jcohenadad** [comment]
The data are _already_ inside the notebook. Related to: #19
