### ISSUE TITLE
What's the red dashed line?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#6]
![image](https://user-images.githubusercontent.com/2482071/124514924-2c2a1180-ddac-11eb-89ea-388489000d05.png)

Also, I would add in the legend what it means

**Comment by zelenkastiot** [comment]
The red line was an attempt to do a reference line like the one we mentioned in our last meeting. 
I can modify it to black and add a name for it in the legend? How should I reference it? 

For example the reference line would look like this: 

![image](https://user-images.githubusercontent.com/37374247/124524953-80111680-ddfd-11eb-9406-c68f22824ba0.png)

And on hover you can get the value of the y-axis: 

![image](https://user-images.githubusercontent.com/37374247/124525113-3d9c0980-ddfe-11eb-98ef-1b202140ae10.png)

**Comment by jcohenadad** [comment]
but what is this reference line? what does it represent? the mean? the median? something else? that’s what needs to be mentioned.
and if the mean: mean of what? all contrasts? only T2w?

**Comment by jcohenadad** [comment]
@zelenkastiot Mathieu clarified what the reference line meant (ie: currently arbitrary, it was just for the purpose of showing what a reference line would like).

So yes: it would be great to have:
- one line (the one you show in https://github.com/courtois-neuromod/anat-processing-book/issues/6#issuecomment-874631895) that represents the mean and standard deviation across all subjects for T1w data. The color of the line should match that of the T1w dots.
- one line that represents the mean and standard deviation across all subjects for T2w data. The color of the line should match that of the T2w dots.

**Comment by jcohenadad** [comment]
hi @zelenkastiot, i was wondering if there was any update on this issue?

**Comment by zelenkastiot** [comment]
Hello @jcohenadad, sorry for this late reply. I had something done for the office hours meeting 2 days ago, but unfortunately, I wasn't able to make it. 

This is something that I whooped up: 

![image](https://user-images.githubusercontent.com/37374247/126915356-c01654df-99b7-44aa-8f91-246ef765068c.png)

I calculated the means for each session, but I didn't know how to name them since for me they are means of means. 
How should I name them? 

And regarding the STD, how do you want it to be displayed? It is easy to calculate but it may look a little cluttered if you had something like this in mind: 
![image](https://user-images.githubusercontent.com/37374247/126915441-b33b8f2f-6771-40a6-bc58-021296ead57c.png)

I actually had in mind to have like two lines (one above, one below the mean) but again I tried it and it looked cluttered as well.

Let me know what you think. If you decide to have the STD left out, then I will push these changes with modified names and close this issue.

**Comment by jcohenadad** [comment]
@zelenkastiot I like this one:
![image](https://user-images.githubusercontent.com/2482071/127079907-0138a778-189d-4206-9a87-e81fb495d976.png)

But could you make the following changes:
- reduce opacity on the STD to mitigate the problem we see for the Angle metric
- Add horizontal lines as discussed in https://github.com/courtois-neuromod/anat-processing-book/issues/7#issuecomment-886267711
- Legend:
  - Remove "Sessions for:"
  - Rename: T1w sessions mean --> T1w mean
  - Rename: T2w sessions mean --> T2w mean

**Comment by zelenkastiot** [comment]
Hey @jcohenadad, I pushed the last version of the plot I had locally. Let me know what you think 😃 

![image](https://user-images.githubusercontent.com/37374247/127139323-681254ce-d7e6-48ce-9678-e587a8dac9d8.png)

**Comment by jcohenadad** [comment]
This issue is now fixed
